<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PassPlat.Aplicacion.Dtos</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PassPlat.Dominio\PassPlat.Dominio.csproj" />
  </ItemGroup>

</Project>
